#!/bin/sh

bat=/sys/class/power_supply/BAT1
per="$(cat "$bat/capacity")"
status="$(cat "$bat/status")"

icon() {

if [ "$per" -gt "90" ]; then
    [ $status = Charging ] && echo "󰂅" && exit
	icon="󰁹"
elif [ "$per" -gt "80" ]; then
    [ $status = Charging ] && echo "󰂊" && exit
	icon="󰂁"
elif [ "$per" -gt "70" ]; then
    [ $status = Charging ] && echo "󰢞" && exit
	icon="󰂀"
elif [ "$per" -gt "60" ]; then
    [ $status = Charging ] && echo "󰂉" && exit
	icon="󰁿"
elif [ "$per" -gt "50" ]; then
    [ $status = Charging ] && echo "󰢝" && exit
	icon="󰁾"
elif [ "$per" -gt "40" ]; then
    [ $status = Charging ] && echo "󰂈" && exit
	icon="󰁽"
elif [ "$per" -gt "30" ]; then
    [ $status = Charging ] && echo "󰂇" && exit
	icon="󰁼"
elif [ "$per" -gt "20" ]; then
    [ $status = Charging ] && echo "󰂆" && exit
	icon="󰁻"
elif [ "$per" -gt "10" ]; then
    [ $status = Charging ] && echo "󰢜" && exit
	icon="󰁺"
	# notify-send -u critical "Battery Low" "Connect Charger"
elif [ "$per" -gt "0" ]; then
    [ $status = Charging ] && echo "󰢟" && exit
	icon="󰂎"
	# notify-send -u critical "Battery Low" "Connect Charger"
else
        echo  && exit
fi
echo "$icon"
}

percent() {
if [ "$per" -gt "99" ]; then
    echo "100"
else 
    echo "$per%"
fi
}

[ "$1" = "icon" ] && icon && exit
# [ "$1" = "percent" ] && percent && exit
exit
