#!/bin/bash

spaces (){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
    nr=1
    test="$(echo $WORKSPACE_WINDOWS | jq --arg nr $nr '.[$nr]')"
    echo $test
    if [ "$test" = "null" ] || [ "$test" -eq "0" ]; then
        echo "no"
    else 
        echo "yes"
    fi
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done

