#!/usr/bin/env bash
if [ "$(pactl list sinks | grep "Mute" | head -$SINK | tail -1 | tail -c 2)" = "o" ]; then
    pactl list sinks | grep '^[[:space:]]Volume:' | \
        head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
else
    echo 0
fi
