#!/bin/bash
SELECTION=$(echo -e "de\nneo\nneo qwertz" | rofi -dmenu -i -p "Which Layout?")
case $SELECTION in
	"de")
		setxkbmap de
		setxkbmap -option caps:escape &
		;;
	"neo")
		setxkbmap de neo
		xcape -e 'ISO_Level3_Shift=Escape' -t 200
		;;
	"neo_qwertz")
		setxkbmap de neo_qwertz
		xcape -e 'ISO_Level3_Shift=Escape' -t 200
		;;
	*)
		echo "Possible inputs: de neo neo_qwertz"
		;;
esac
xset r rate 300 40 &
