#!/bin/bash
LAYOUT=$(setxkbmap -query | grep layout | awk '{ print $NF }')
case $LAYOUT in
	"de")
		VARIANT=$(setxkbmap -query | grep variant | awk '{ print $NF }')
		case $VARIANT in
			"neo")
				echo " neo"
				;;
			"neo_qwertz")
				echo " neo qwertz"
				;;
			*)
				echo " $LAYOUT"
				;;
		esac
		;;
	*)
		echo " $LAYOUT"
		;;
esac
