[General]
check_for_update=false
hide_on_close=false
minimize_to_systray=false
show_systray_icon=false
start_minimized=false

[content]
appearance=@Variant(\0\0\0\x7f\0\0\0\x12\x43ontentAppearance\0\0\0\0\0)
custom_css_file=
dark_mode=true
default_fixed_font_size=15
default_font_family=sans-serif
default_font_size=17
disable_ad=true
external_link_policy=@Variant(\0\0\0\x7f\0\0\0\x13\x45xternalLinkPolicy\0\0\0\0\0)
fixed_font_family=SauceCodePro Nerd Font Mono
highlight_on_navigate=true
minimum_font_size=0
sans_serif_font_family=Quicksand Medium
serif_font_family=Nimbus Roman
smooth_scrolling=true

[docsets]
path=/home/julius/.local/share/Zeal/Zeal/docsets

[global_shortcuts]
show=

[internal]
install_id=627b84b9-46f9-4b0a-8549-756e588a3da6
version=0.7.2

[proxy]
authenticate=false
host=
ignore_ssl_errors=false
password=
port=0
type=1
username=

[search]
fuzzy_search_enabled=false

[state]
splitter_geometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xbf\0\0\x2\x8d\0\xff\xff\xff\xff\x1\0\0\0\x1\0)
toc_splitter_state=@ByteArray()
window_geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\xe\xe8\0\0\x3\xc4\0\0\x14\xe9\0\0\x5\x99\0\0\xe\xe8\0\0\x3\xc4\0\0\x14\xe9\0\0\x5\x99\0\0\0\x1\0\0\0\0\rp\0\0\xe\xe8\0\0\x3\xc4\0\0\x14\xe9\0\0\x5\x99)

[tabs]
open_new_tab_after_active=false
