#!/usr/bin/sh

sxhkd &
udiskie &
batsignal &
picom &
./.fehbg &
./.config/polybar/launch.sh &
#Obs camer
sudo modprobe v4l2loopback devices=1 exclusive_caps=1 &
#Screen lock
xset s 600 600 &
xss-lock lockscreen -l &
#Fix X shaped xursor
xsetroot -cursor_name left_ptr
#Touchpad
xinput --set-prop "ELAN1300:00 04F3:3057 Touchpad" "libinput Accel Speed" -1
xinput --set-prop "ELAN1300:00 04F3:3057 Touchpad" "libinput Tapping Enabled" 1
xinput --set-prop "ELAN1300:00 04F3:3057 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "ELAN1300:00 04F3:3057 Touchpad" "Coordinate Transformation Matrix" 18, 0, 0, 0, 18, 0, 0, 0, 1

setxkbmap -option caps:escape &
xset r rate 300 40 &

#bspc wm -O HDMI-0 DVI-I-0
#bspc monitor HDMI-0 -d 1 2 3 4 5
#bspc monitor DVI-I-0 -d 6 7 8 9 10
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
xrandr --output DP-0 --mode 3440x1440 -r 99.98

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Theming
bspc config normal_border_color "#504945"
bspc config focused_border_color "#d65d0e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
